site_name: Lean Prover 中文文档
site_url: https://leanprover.cn
repo_url: https://github.com/Lean-zh/Lean-zh.github.io
repo_name: Lean-zh
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: green
    accent: light green
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
        - locale: zh
          name: 中文
          default: true
          build: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: friendly
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - assets/css/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css

extra:
  version:
    provider: mike
    default: latest
    alias: true

nav:
  - 主页: index.md
  - 文档教程:
    - Lean4 安装教程及 Lake 环境管理: tutorial/install.md
    - Lean4Game 教程: tutorial/lean4game.md
    - LeanDojo 使用教程: tutorial/lean-dojo.md
    - Lake 文档: references/lake-doc.md    
  - 其他链接: links.md

